name: Build & deploy blog to GCP bucket
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - run: npm install
      - run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Configure authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/51450984193/locations/global/workloadIdentityPools/github/providers/github
          service_account: github-actions-service-account@astro-blog-446207.iam.gserviceaccount.com
          audience: https://github.com/mchaitanya/astro-blog

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 390.0.0'
          
      - name: Copy files to Google Cloud Storage
        run: |
          gsutil -m cp -r dist/* gs://astro-blog-dist/
      
      - run: echo "üçè This job's status is ${{ job.status }}."
